#ifndef INTERFACE_REPLICA_H
#define INTERFACE_REPLICA_H

// This is an autogenerated file.
// Do not edit this file, any changes made will be lost the next time it is generated.

#include <QtCore/qobject.h>
#include <QtCore/qdatastream.h>
#include <QtCore/qvariant.h>
#include <QtCore/qmetatype.h>

#include <QtRemoteObjects/qremoteobjectnode.h>
#include <QtRemoteObjects/qremoteobjectpendingcall.h>
#include <QtRemoteObjects/qremoteobjectreplica.h>


class InterfaceReplica : public QRemoteObjectReplica
{
    Q_OBJECT
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_TYPE, "Interface")
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_SIGNATURE, "75b57c6884e381d90377ef07ff2c79ea424d283e")

public:
    InterfaceReplica() : QRemoteObjectReplica() { initialize(); }
    static void registerMetatypes()
    {
        static bool initialized = false;
        if (initialized)
            return;
        initialized = true;
    }

private:
    InterfaceReplica(QRemoteObjectNode *node, const QString &name = QString())
        : QRemoteObjectReplica(ConstructWithNode)
    {
        initializeNode(node, name);
    }

    void initialize() override
    {
        InterfaceReplica::registerMetatypes();
        QVariantList properties;
        properties.reserve(0);
        setProperties(properties);
    }

public:
    virtual ~InterfaceReplica() {}


public Q_SLOTS:
    void addCommand_slot(QString pURL)
    {
        static int __repc_index = InterfaceReplica::staticMetaObject.indexOfSlot("addCommand_slot(QString)");
        QVariantList __repc_args;
        __repc_args
            << QVariant::fromValue(pURL)
        ;
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void rmCommand_slot(QString pURL)
    {
        static int __repc_index = InterfaceReplica::staticMetaObject.indexOfSlot("rmCommand_slot(QString)");
        QVariantList __repc_args;
        __repc_args
            << QVariant::fromValue(pURL)
        ;
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }

private:
    friend class QT_PREPEND_NAMESPACE(QRemoteObjectNode);
};

#if (QT_VERSION < QT_VERSION_CHECK(5, 5, 0))
#endif


QT_BEGIN_NAMESPACE
QT_END_NAMESPACE


#endif // INTERFACE_REPLICA_H
