#ifndef INTERFACE_SOURCE_H
#define INTERFACE_SOURCE_H

// This is an autogenerated file.
// Do not edit this file, any changes made will be lost the next time it is generated.

#include <QtCore/qobject.h>
#include <QtCore/qdatastream.h>
#include <QtCore/qvariant.h>
#include <QtCore/qmetatype.h>

#include <QtRemoteObjects/qremoteobjectnode.h>
#include <QtRemoteObjects/qremoteobjectsource.h>


class InterfaceSource : public QObject
{
    Q_OBJECT
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_TYPE, "Interface")
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_SIGNATURE, "75b57c6884e381d90377ef07ff2c79ea424d283e")

public:
    explicit InterfaceSource(QObject *parent = nullptr) : QObject(parent)
    {
    }

public:
    virtual ~InterfaceSource() {}


public Q_SLOTS:
    virtual void addCommand_slot(QString pURL) = 0;
    virtual void rmCommand_slot(QString pURL) = 0;

private:
    friend class QT_PREPEND_NAMESPACE(QRemoteObjectNode);
};

#if (QT_VERSION < QT_VERSION_CHECK(5, 5, 0))
#endif


class InterfaceSimpleSource : public InterfaceSource
{
    Q_OBJECT

public:
    explicit InterfaceSimpleSource(QObject *parent = nullptr) : InterfaceSource(parent)
    {
    }

public:
    virtual ~InterfaceSimpleSource() {}


private:
};


template <class ObjectType>
struct InterfaceSourceAPI : public SourceApiMap
{
    InterfaceSourceAPI(ObjectType *object, const QString &name = QStringLiteral("Interface"))
        : SourceApiMap(), m_name(name)
    {
        Q_UNUSED(object);
        m_enums[0] = 0;
        m_properties[0] = 0;
        m_signals[0] = 0;
        m_methods[0] = 2;
        m_methods[1] = QtPrivate::qtro_method_index<ObjectType>(&ObjectType::addCommand_slot, static_cast<void (QObject::*)(QString)>(0),"addCommand_slot(QString)",m_methodArgCount+0,&m_methodArgTypes[0]);
        m_methods[2] = QtPrivate::qtro_method_index<ObjectType>(&ObjectType::rmCommand_slot, static_cast<void (QObject::*)(QString)>(0),"rmCommand_slot(QString)",m_methodArgCount+1,&m_methodArgTypes[1]);
    }

    QString name() const override { return m_name; }
    QString typeName() const override { return QStringLiteral("Interface"); }
    int enumCount() const override { return m_enums[0]; }
    int propertyCount() const override { return m_properties[0]; }
    int signalCount() const override { return m_signals[0]; }
    int methodCount() const override { return m_methods[0]; }
    int sourceEnumIndex(int index) const override
    {
        if (index < 0 || index >= m_enums[0])
            return -1;
        return m_enums[index+1];
    }
    int sourcePropertyIndex(int index) const override
    {
        if (index < 0 || index >= m_properties[0])
            return -1;
        return m_properties[index+1];
    }
    int sourceSignalIndex(int index) const override
    {
        if (index < 0 || index >= m_signals[0])
            return -1;
        return m_signals[index+1];
    }
    int sourceMethodIndex(int index) const override
    {
        if (index < 0 || index >= m_methods[0])
            return -1;
        return m_methods[index+1];
    }
    int signalParameterCount(int index) const override { Q_UNUSED(index); return -1; }
    int signalParameterType(int sigIndex, int paramIndex) const override
    { Q_UNUSED(sigIndex); Q_UNUSED(paramIndex); return -1; }
    int methodParameterCount(int index) const override
    {
        if (index < 0 || index >= m_methods[0])
            return -1;
        return m_methodArgCount[index];
    }
    int methodParameterType(int methodIndex, int paramIndex) const override
    {
        if (methodIndex < 0 || methodIndex >= m_methods[0] || paramIndex < 0 || paramIndex >= m_methodArgCount[methodIndex])
            return -1;
        return m_methodArgTypes[methodIndex][paramIndex];
    }
    int propertyIndexFromSignal(int index) const override
    {
        Q_UNUSED(index);
        return -1;
    }
    int propertyRawIndexFromSignal(int index) const override
    {
        Q_UNUSED(index);
        return -1;
    }
    const QByteArray signalSignature(int index) const override
    {
        Q_UNUSED(index);
        return QByteArrayLiteral("");
    }
    QList<QByteArray> signalParameterNames(int index) const override
    {
        if (index < 0 || index >= m_signals[0])
            return QList<QByteArray>();
        return ObjectType::staticMetaObject.method(m_signals[index + 1]).parameterNames();
    }
    const QByteArray methodSignature(int index) const override
    {
        switch (index) {
        case 0: return QByteArrayLiteral("addCommand_slot(QString)");
        case 1: return QByteArrayLiteral("rmCommand_slot(QString)");
        }
        return QByteArrayLiteral("");
    }
    QMetaMethod::MethodType methodType(int) const override
    {
        return QMetaMethod::Slot;
    }
    QList<QByteArray> methodParameterNames(int index) const override
    {
        if (index < 0 || index >= m_methods[0])
            return QList<QByteArray>();
        return ObjectType::staticMetaObject.method(m_methods[index + 1]).parameterNames();
    }
    const QByteArray typeName(int index) const override
    {
        switch (index) {
        case 0: return QByteArrayLiteral("void");
        case 1: return QByteArrayLiteral("void");
        }
        return QByteArrayLiteral("");
    }
    QByteArray objectSignature() const override { return QByteArray{"75b57c6884e381d90377ef07ff2c79ea424d283e"}; }

    int m_enums[1];
    int m_properties[1];
    int m_signals[1];
    int m_methods[3];
    const QString m_name;
    int m_methodArgCount[2];
    const int* m_methodArgTypes[2];
};

QT_BEGIN_NAMESPACE
QT_END_NAMESPACE


#endif // INTERFACE_SOURCE_H
